#!/bin/bash

deepspeed llava/train/train_mem.py \
    --lora_enable True --lora_r 256 --lora_alpha 512 \
    --mm_projector_lr 2e-5 \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path /mnt/workspace/workgroup/chengxiang/models/llava-v1.6-34b \
    --version chatml_direct \
    --data_path /mnt/workspace/workgroup/chengxiang/datasets/aicity2024/process/mixed_wts_bdd_trainval.json \
    --image_folder /mnt/workspace/workgroup/chenghao/video_analysis/dataset \
    --vision_tower /mnt/workspace/workgroup/chengxiang/models/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir /mnt/workspace/workgroup/chengxiang/work_dirs/llava1_6-34b-aicity-lora256-pad-multiround-0321 \
    --num_train_epochs 2 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "epoch" \
    --save_total_limit 6 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 4096 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to tensorboard
